parameters:
- name: timeout
  type: number
  default: 360

- name: log_artifact_name
  type: string

- name: docker_sonic_vs_name
  type: string
  default: docker-sonic-vs

- name: asan
  type: boolean
  default: false

jobs:
- job:
  displayName: vstest
  timeoutInMinutes: ${{ parameters.timeout }}

  pool: sonictest

  steps:
  - script: |
      set -ex
      ls -A1 | xargs -I{} sudo rm -rf {}
      sudo apt-get purge libswsscommon python3-swsscommon || true
    displayName: "Clean workspace"
  - checkout: self
    clean: true
    displayName: "Checkout sonic-sairedis"
  - checkout: sonic-swss
    clean: true
    displayName: "Checkout sonic-swss"
  - script: |
      set -ex
      cd sonic-swss
      git checkout $(BUILD_BRANCH)
    displayName: Set up sonic-swss branch
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: ${{ parameters.docker_sonic_vs_name }}
      path: $(Build.ArtifactStagingDirectory)/download
    displayName: "Download pre-stage built ${{ parameters.docker_sonic_vs_name }}"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-swss-common
      artifact: sonic-swss-common.amd64.ubuntu22_04
      path: $(Build.ArtifactStagingDirectory)/download
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      allowPartiallySucceededBuilds: true
    displayName: "Download sonic swss common deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: sonic-net.sonic-buildimage-ubuntu22.04
      artifact: sonic-buildimage.amd64.ubuntu22_04
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/$(BUILD_BRANCH)'
      path: $(Build.ArtifactStagingDirectory)/download
    displayName: "Download sonic buildimage ubuntu deb packages"

  - script: |
      set -ex
      # install packages for vs test
      sudo pip3 install pytest flaky exabgp docker redis

      # install packages for kvm test
      sudo apt-get update
      sudo apt --fix-broken install
      sudo apt-get -o DPkg::Lock::Timeout=600 install -y libvirt-clients \
          qemu \
          openvswitch-switch \
          net-tools \
          bridge-utils \
          vlan \
          python3-libvirt \
          libzmq3-dev \
          libzmq5 \
          libboost-serialization1.74.0 \
          libboost1.74-dev \
          libboost-dev \
          libhiredis0.14 \
          libyang-dev \
          uuid-dev

      sudo sonic-sairedis/.azure-pipelines/build_and_install_module.sh

      sudo apt install -y $(Build.ArtifactStagingDirectory)/download/libprotobuf*_amd64.deb $(Build.ArtifactStagingDirectory)/download/libprotobuf-lite*_amd64.deb $(Build.ArtifactStagingDirectory)/download/python3-protobuf*_amd64.deb
      sudo apt install -y $(Build.ArtifactStagingDirectory)/download/libdashapi*.deb $(Build.ArtifactStagingDirectory)/download/libswsscommon_1.0.0_amd64.deb $(Build.ArtifactStagingDirectory)/download/python3-swsscommon_1.0.0_amd64.deb

    displayName: "Install dependencies"

  - script: |
      set -ex
      sudo docker load -i $(Build.ArtifactStagingDirectory)/download/docker-sonic-vs.gz
      docker ps
      ip netns list
      pushd sonic-swss/tests
      params=''
      if [ '${{ parameters.asan }}' == True ]; then
        params='--graceful-stop'
      fi
      all_tests=$(ls test_*.py)
      all_tests="${all_tests} p4rt dash"
      RETRY=3
      IMAGE_NAME=docker-sonic-vs:$(Build.DefinitionName).$(Build.BuildNumber).asan-${{ parameters.asan }}
      echo $all_tests | xargs -n 1 | xargs -P 8 -I TEST_MODULE sudo ./run-tests.sh "$IMAGE_NAME" "$params" "TEST_MODULE" "$RETRY"

      rm -rf $(Build.ArtifactStagingDirectory)/download
    displayName: "Run vs tests"
    ${{ if or(ne(variables['Build.Reason'], 'PullRequest'), eq(parameters.asan, true)) }}:
      continueOnError: true

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/tr.xml'
      testRunTitle: vstest
    condition: always()

  - script: |
      if [ -d sonic-swss/tests/log ]; then
        cp -r sonic-swss/tests/log $(Build.ArtifactStagingDirectory)/
        if [ '${{ parameters.asan }}' == True ]; then
          cp -vr sonic-swss/tests/log/*/log/asan $(Build.ArtifactStagingDirectory)/
        fi
      fi
    displayName: "Collect logs"
    condition: always()

  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: ${{ parameters.log_artifact_name }}@$(System.JobAttempt)
    displayName: "Publish logs"
    condition: always()

  - publish: $(Build.ArtifactStagingDirectory)/asan
    artifact: asan-reports
    displayName: "Publish ASAN reports"
    condition: eq('${{ parameters.asan }}', true)

  - script: |
      if [ "$(ls -A $(Build.ArtifactStagingDirectory)/asan)" ]; then
        echo "There are issues reported by ASAN"
        exit 1
      else
        echo "No issues reported by ASAN"
      fi
    displayName: "Check ASAN reports"
    condition: eq('${{ parameters.asan }}', true)
    continueOnError: true
